[package]
name = "liquid-helper-proxy"
version = "0.2.0"
authors = ["Bassam Monib <bassam.munib@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "liquid-helper-proxy"
path = "bin/main.rs"
bench = false
doctest = false
test = false