[package]
name = "curve-token-utils"
version = "0.1.0"
edition = "2018"
authors = ["Nouman Nadeem<nouman.nadeem.zafar@scytalelabs.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
casper_types_derive = "0.1.0"
casperlabs-contract-utils = "0.1.0"
renvm-sig = "0.1.1"
hex = "0.4.3"

[features]
default = ["casper-contract/std", "casper-types/std", "casper-contract/test-support"]